# Generated by Django 4.2 on 2023-05-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='variation_value',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='variation_category',
        ),
    ]
